
name: "Regenerate WhoAmI table"

on:
  workflow_dispatch:
  push:
    paths:
      - 'whoami.yml'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
            python-version: '3.12'
      - name: Run gen-whoami-table.py
        run: |
                  uv run .github/workflows/gen-whoami-table.py ./whoami.yml
      - name: Commit changes
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add whoami.md
            if ! git diff --cached --quiet; then
            git commit -m "Update device WhoAmI table"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git push
            else
            echo "No changes to commit."
            fi
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}